# Generated by Django 4.1.4 on 2022-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='qty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
